# calendar_ui.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarViewWidget(object):
    def setupUi(self, CalendarViewWidget):
        CalendarViewWidget.setObjectName("CalendarViewWidget")
        CalendarViewWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalendarViewWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(CalendarViewWidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)

        self.retranslateUi(CalendarViewWidget)
        QtCore.QMetaObject.connectSlotsByName(CalendarViewWidget)

    def retranslateUi(self, CalendarViewWidget):
        pass
