#room_map_ui.py
# This file is auto-generated by PyQt5's UI code generator from a .ui file
# It defines the layout and widgets for the RoomMapWidget, which displays a map of rooms
# and their statuses for a selected date.
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoomMapWidget(object):
    def setupUi(self, RoomMapWidget):
        RoomMapWidget.setObjectName("RoomMapWidget")
        RoomMapWidget.resize(814, 550)
        self.gridLayout_2 = QtWidgets.QGridLayout(RoomMapWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.titleLabel = QtWidgets.QLabel(RoomMapWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)

        self.retranslateUi(RoomMapWidget)
        QtCore.QMetaObject.connectSlotsByName(RoomMapWidget)

    def retranslateUi(self, RoomMapWidget):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("RoomMapWidget", "[Selected Date]"))
